// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"cli.mdx": () => import("../content/docs/cli.mdx?collection=docs"), "index.mdx": () => import("../content/docs/index.mdx?collection=docs"), "installation.mdx": () => import("../content/docs/installation.mdx?collection=docs"), "blocks/bitcoin-avatar.mdx": () => import("../content/docs/blocks/bitcoin-avatar.mdx?collection=docs"), "blocks/buy-listing.mdx": () => import("../content/docs/blocks/buy-listing.mdx?collection=docs"), "blocks/connect-wallet.mdx": () => import("../content/docs/blocks/connect-wallet.mdx?collection=docs"), "blocks/create-listing.mdx": () => import("../content/docs/blocks/create-listing.mdx?collection=docs"), "blocks/deploy-token.mdx": () => import("../content/docs/blocks/deploy-token.mdx?collection=docs"), "blocks/follow-button.mdx": () => import("../content/docs/blocks/follow-button.mdx?collection=docs"), "blocks/friend-button.mdx": () => import("../content/docs/blocks/friend-button.mdx?collection=docs"), "blocks/identity-selector.mdx": () => import("../content/docs/blocks/identity-selector.mdx?collection=docs"), "blocks/inscribe-file.mdx": () => import("../content/docs/blocks/inscribe-file.mdx?collection=docs"), "blocks/like-button.mdx": () => import("../content/docs/blocks/like-button.mdx?collection=docs"), "blocks/market-grid.mdx": () => import("../content/docs/blocks/market-grid.mdx?collection=docs"), "blocks/mnemonic-flow.mdx": () => import("../content/docs/blocks/mnemonic-flow.mdx?collection=docs"), "blocks/ordinals-grid.mdx": () => import("../content/docs/blocks/ordinals-grid.mdx?collection=docs"), "blocks/post-button.mdx": () => import("../content/docs/blocks/post-button.mdx?collection=docs"), "blocks/profile-card.mdx": () => import("../content/docs/blocks/profile-card.mdx?collection=docs"), "blocks/receive-address.mdx": () => import("../content/docs/blocks/receive-address.mdx?collection=docs"), "blocks/send-bsv.mdx": () => import("../content/docs/blocks/send-bsv.mdx?collection=docs"), "blocks/social-feed.mdx": () => import("../content/docs/blocks/social-feed.mdx?collection=docs"), "blocks/sync-terminal.mdx": () => import("../content/docs/blocks/sync-terminal.mdx?collection=docs"), "blocks/token-list.mdx": () => import("../content/docs/blocks/token-list.mdx?collection=docs"), "blocks/transaction-history.mdx": () => import("../content/docs/blocks/transaction-history.mdx?collection=docs"), "components/authentication.mdx": () => import("../content/docs/components/authentication.mdx?collection=docs"), "components/market.mdx": () => import("../content/docs/components/market.mdx?collection=docs"), "components/social.mdx": () => import("../content/docs/components/social.mdx?collection=docs"), "components/step-indicator.mdx": () => import("../content/docs/components/step-indicator.mdx?collection=docs"), "components/wallet.mdx": () => import("../content/docs/components/wallet.mdx?collection=docs"), }),
};
export default browserCollections;