import { promises as fs } from "fs"
import path from "path"
import { registry } from "../registry/index.js"

// Map block names to their primary export names
const EXPORT_NAMES: Record<string, string> = {
  "step-indicator": "StepIndicator",
  "connect-wallet": "ConnectWallet",
  "send-bsv": "SendBsv",
  "token-list": "TokenList",
  "post-button": "PostButton",
  "like-button": "LikeButton",
  "follow-button": "FollowButton",
  "friend-button": "FriendButton",
  "social-feed": "SocialFeed",
  "inscribe-file": "InscribeFile",
  "deploy-token": "DeployToken",
  "create-listing": "CreateListing",
  "buy-listing": "BuyListing",
  "ordinals-grid": "OrdinalsGrid",
  "market-grid": "MarketGrid",
  "bitcoin-avatar": "BitcoinAvatar",
  "profile-card": "ProfileCard",
  "identity-selector": "IdentitySelector",
  "receive-address": "ReceiveAddress",
  "transaction-history": "TransactionHistory",
  "mnemonic-flow": "MnemonicFlow",
  "sync-terminal": "SyncTerminal",
  "lock-bsv": "LockBsv",
  "sweep-wallet": "SweepWallet",
  "send-bsv21": "SendBsv21",
  "unlock-wallet": "UnlockWallet",
  "wallet-overview": "WalletOverview",
  "opns-manager": "OpnsManager",
  "theme-token-provider": "ThemeTokenProvider",
  "bigblocks-provider": "BigBlocksProvider",
  "bitcoin-signin": "BitcoinSignin",
  "oauth-callback": "OAuthCallback",
  "cloud-backup-prompt": "CloudBackupPrompt",
}

async function buildRegistryIndex() {
  let index = `/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.mts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {`

  // Add all registry items (blocks + components)
  for (const item of registry.items) {
    const componentPath = item.files?.[0]?.path
      ? `@/registry/bigblocks/${item.files[0].path}`
      : ""

    const exportName = EXPORT_NAMES[item.name] || "default"

    index += `
  "${item.name}": {
    name: "${item.name}",
    title: "${item.title || item.name}",
    description: ${JSON.stringify(item.description ?? "")},
    type: "${item.type}",
    registryDependencies: ${JSON.stringify(item.registryDependencies ?? undefined)},
    files: [${item.files?.map((file) => {
      const f = typeof file === "string" ? { path: file, type: "registry:ui" } : file
      return `{
      path: "registry/bigblocks/${f.path}",
      type: "${f.type}",
      target: ""
    }`
    }).join(", ")}],
    component: ${
      componentPath
        ? `React.lazy(async () => {
      const mod = await import("${componentPath}")
      return { default: mod.${exportName} || mod.default }
    })`
        : "null"
    },
    categories: ${JSON.stringify(item.categories ?? [])},
    dependencies: ${JSON.stringify(item.dependencies ?? undefined)},
  },`
  }

  // Add all example/demo components
  for (const example of registry.examples) {
    const examplePath = example.files?.[0]?.path
      ? `@/registry/bigblocks/${example.files[0].path}`
      : ""

    index += `
  "${example.name}": {
    name: "${example.name}",
    type: "registry:example",
    registryDependencies: ${JSON.stringify(example.registryDependencies ?? [])},
    files: [${example.files?.map((file) => {
      const f = typeof file === "string" ? { path: file, type: "registry:example" } : file
      return `{
      path: "registry/bigblocks/${f.path}",
      type: "${f.type}",
      target: ""
    }`
    }).join(", ")}],
    component: ${
      examplePath
        ? `React.lazy(() => import("${examplePath}"))`
        : "null"
    },
    categories: ["examples"],
  },`
  }

  index += `
}
`

  console.log(`✅ ${registry.items.length} items + ${registry.examples.length} examples`)

  await fs.writeFile(
    path.join(process.cwd(), "registry/__index__.tsx"),
    index
  )

  console.log("✅ Registry index generated")
}

async function main() {
  await buildRegistryIndex()
}

main().catch(console.error)
