/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.mts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "step-indicator": {
    name: "step-indicator",
    title: "Step Indicator",
    description: "Display progress through multi-step processes with horizontal and vertical variants",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/bigblocks/ui/step-indicator.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bigblocks/ui/step-indicator.tsx")
      return { default: mod.StepIndicator || mod.default }
    }),
    categories: ["ui-components"],
    dependencies: ["@radix-ui/react-icons"],
  },
  "connect-wallet": {
    name: "connect-wallet",
    title: "Connect Wallet",
    description: "Wallet connection button with provider selection and connected-state dropdown",
    type: "registry:block",
    registryDependencies: undefined,
    files: [{
      path: "registry/bigblocks/blocks/connect-wallet/index.tsx",
      type: "registry:block",
      target: ""
    }, {
      path: "registry/bigblocks/blocks/connect-wallet/ui.tsx",
      type: "registry:component",
      target: ""
    }, {
      path: "registry/bigblocks/blocks/connect-wallet/use-connect-wallet.ts",
      type: "registry:hook",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bigblocks/blocks/connect-wallet/index.tsx")
      return { default: mod.ConnectWallet || mod.default }
    }),
    categories: ["wallet"],
    dependencies: undefined,
  },
  "send-bsv": {
    name: "send-bsv",
    title: "Send BSV",
    description: "Complete send BSV block with trigger variants and dialog form",
    type: "registry:block",
    registryDependencies: undefined,
    files: [{
      path: "registry/bigblocks/blocks/send-bsv/index.tsx",
      type: "registry:block",
      target: ""
    }, {
      path: "registry/bigblocks/blocks/send-bsv/send-bsv-trigger.tsx",
      type: "registry:component",
      target: ""
    }, {
      path: "registry/bigblocks/blocks/send-bsv/send-bsv-dialog.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bigblocks/blocks/send-bsv/index.tsx")
      return { default: mod.SendBsv || mod.default }
    }),
    categories: ["wallet"],
    dependencies: undefined,
  },
  "token-list": {
    name: "token-list",
    title: "Token List",
    description: "BSV20/BSV21 token holdings list with balances and icons",
    type: "registry:block",
    registryDependencies: undefined,
    files: [{
      path: "registry/bigblocks/blocks/token-list/index.tsx",
      type: "registry:block",
      target: ""
    }, {
      path: "registry/bigblocks/blocks/token-list/token-list-ui.tsx",
      type: "registry:component",
      target: ""
    }, {
      path: "registry/bigblocks/blocks/token-list/use-token-list.ts",
      type: "registry:hook",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bigblocks/blocks/token-list/index.tsx")
      return { default: mod.TokenList || mod.default }
    }),
    categories: ["wallet"],
    dependencies: undefined,
  },
  "receive-address": {
    name: "receive-address",
    title: "Receive Address",
    description: "QR code and deposit address display with clipboard copy and optional address rotation",
    type: "registry:block",
    registryDependencies: undefined,
    files: [{
      path: "registry/bigblocks/blocks/receive-address/index.tsx",
      type: "registry:block",
      target: ""
    }, {
      path: "registry/bigblocks/blocks/receive-address/receive-address-ui.tsx",
      type: "registry:component",
      target: ""
    }, {
      path: "registry/bigblocks/blocks/receive-address/use-receive-address.ts",
      type: "registry:hook",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bigblocks/blocks/receive-address/index.tsx")
      return { default: mod.ReceiveAddress || mod.default }
    }),
    categories: ["wallet"],
    dependencies: undefined,
  },
  "transaction-history": {
    name: "transaction-history",
    title: "Transaction History",
    description: "Transaction list with status indicators, amounts, relative dates, and pagination",
    type: "registry:block",
    registryDependencies: undefined,
    files: [{
      path: "registry/bigblocks/blocks/transaction-history/index.tsx",
      type: "registry:block",
      target: ""
    }, {
      path: "registry/bigblocks/blocks/transaction-history/transaction-history-ui.tsx",
      type: "registry:component",
      target: ""
    }, {
      path: "registry/bigblocks/blocks/transaction-history/use-transaction-history.ts",
      type: "registry:hook",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bigblocks/blocks/transaction-history/index.tsx")
      return { default: mod.TransactionHistory || mod.default }
    }),
    categories: ["wallet"],
    dependencies: undefined,
  },
  "mnemonic-flow": {
    name: "mnemonic-flow",
    title: "Mnemonic Flow",
    description: "Multi-mode seed phrase display and input block with create, display, import, and verify modes",
    type: "registry:block",
    registryDependencies: undefined,
    files: [{
      path: "registry/bigblocks/blocks/mnemonic-flow/index.tsx",
      type: "registry:block",
      target: ""
    }, {
      path: "registry/bigblocks/blocks/mnemonic-flow/mnemonic-flow-ui.tsx",
      type: "registry:component",
      target: ""
    }, {
      path: "registry/bigblocks/blocks/mnemonic-flow/mnemonic-grid-ui.tsx",
      type: "registry:component",
      target: ""
    }, {
      path: "registry/bigblocks/blocks/mnemonic-flow/use-mnemonic-flow.ts",
      type: "registry:hook",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bigblocks/blocks/mnemonic-flow/index.tsx")
      return { default: mod.MnemonicFlow || mod.default }
    }),
    categories: ["wallet"],
    dependencies: undefined,
  },
  "lock-bsv": {
    name: "lock-bsv",
    title: "Lock BSV",
    description: "Time-lock BSV until a future block height with lock form, summary, and unlock for matured locks",
    type: "registry:block",
    registryDependencies: undefined,
    files: [{
      path: "registry/bigblocks/blocks/lock-bsv/index.tsx",
      type: "registry:block",
      target: ""
    }, {
      path: "registry/bigblocks/blocks/lock-bsv/lock-bsv-ui.tsx",
      type: "registry:component",
      target: ""
    }, {
      path: "registry/bigblocks/blocks/lock-bsv/use-lock-bsv.ts",
      type: "registry:hook",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bigblocks/blocks/lock-bsv/index.tsx")
      return { default: mod.LockBsv || mod.default }
    }),
    categories: ["wallet"],
    dependencies: undefined,
  },
  "sweep-wallet": {
    name: "sweep-wallet",
    title: "Sweep Wallet",
    description: "Sweep assets from a WIF private key into the connected wallet with scan and progress",
    type: "registry:block",
    registryDependencies: undefined,
    files: [{
      path: "registry/bigblocks/blocks/sweep-wallet/index.tsx",
      type: "registry:block",
      target: ""
    }, {
      path: "registry/bigblocks/blocks/sweep-wallet/sweep-wallet-ui.tsx",
      type: "registry:component",
      target: ""
    }, {
      path: "registry/bigblocks/blocks/sweep-wallet/use-sweep-wallet.ts",
      type: "registry:hook",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bigblocks/blocks/sweep-wallet/index.tsx")
      return { default: mod.SweepWallet || mod.default }
    }),
    categories: ["wallet"],
    dependencies: undefined,
  },
  "send-bsv21": {
    name: "send-bsv21",
    title: "Send BSV21",
    description: "Token send form with selector dropdown, decimal-aware amount input, and confirmation flow",
    type: "registry:block",
    registryDependencies: undefined,
    files: [{
      path: "registry/bigblocks/blocks/send-bsv21/index.tsx",
      type: "registry:block",
      target: ""
    }, {
      path: "registry/bigblocks/blocks/send-bsv21/send-bsv21-ui.tsx",
      type: "registry:component",
      target: ""
    }, {
      path: "registry/bigblocks/blocks/send-bsv21/use-send-bsv21.ts",
      type: "registry:hook",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bigblocks/blocks/send-bsv21/index.tsx")
      return { default: mod.SendBsv21 || mod.default }
    }),
    categories: ["wallet"],
    dependencies: undefined,
  },
  "unlock-wallet": {
    name: "unlock-wallet",
    title: "Unlock Wallet",
    description: "Passphrase and biometric unlock screen with Touch ID support and failed attempt tracking",
    type: "registry:block",
    registryDependencies: undefined,
    files: [{
      path: "registry/bigblocks/blocks/unlock-wallet/index.tsx",
      type: "registry:block",
      target: ""
    }, {
      path: "registry/bigblocks/blocks/unlock-wallet/unlock-wallet-ui.tsx",
      type: "registry:component",
      target: ""
    }, {
      path: "registry/bigblocks/blocks/unlock-wallet/use-unlock-wallet.ts",
      type: "registry:hook",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bigblocks/blocks/unlock-wallet/index.tsx")
      return { default: mod.UnlockWallet || mod.default }
    }),
    categories: ["wallet"],
    dependencies: undefined,
  },
  "wallet-overview": {
    name: "wallet-overview",
    title: "Wallet Overview",
    description: "Wallet dashboard card with BSV balance, privacy toggle, addresses, and send/receive actions",
    type: "registry:block",
    registryDependencies: undefined,
    files: [{
      path: "registry/bigblocks/blocks/wallet-overview/index.tsx",
      type: "registry:block",
      target: ""
    }, {
      path: "registry/bigblocks/blocks/wallet-overview/wallet-overview-ui.tsx",
      type: "registry:component",
      target: ""
    }, {
      path: "registry/bigblocks/blocks/wallet-overview/use-wallet-overview.ts",
      type: "registry:hook",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bigblocks/blocks/wallet-overview/index.tsx")
      return { default: mod.WalletOverview || mod.default }
    }),
    categories: ["wallet"],
    dependencies: undefined,
  },
  "sync-terminal": {
    name: "sync-terminal",
    title: "Sync Terminal",
    description: "Monospace event log for blockchain sync activity with colour-coded severity levels",
    type: "registry:block",
    registryDependencies: undefined,
    files: [{
      path: "registry/bigblocks/blocks/sync-terminal/index.tsx",
      type: "registry:block",
      target: ""
    }, {
      path: "registry/bigblocks/blocks/sync-terminal/sync-terminal-ui.tsx",
      type: "registry:component",
      target: ""
    }, {
      path: "registry/bigblocks/blocks/sync-terminal/use-sync-terminal.ts",
      type: "registry:hook",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bigblocks/blocks/sync-terminal/index.tsx")
      return { default: mod.SyncTerminal || mod.default }
    }),
    categories: ["developer"],
    dependencies: undefined,
  },
  "post-button": {
    name: "post-button",
    title: "Post Button",
    description: "Create on-chain BSocial posts with compose dialog",
    type: "registry:block",
    registryDependencies: undefined,
    files: [{
      path: "registry/bigblocks/blocks/post-button/index.tsx",
      type: "registry:block",
      target: ""
    }, {
      path: "registry/bigblocks/blocks/post-button/ui.tsx",
      type: "registry:component",
      target: ""
    }, {
      path: "registry/bigblocks/blocks/post-button/use-post.ts",
      type: "registry:hook",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bigblocks/blocks/post-button/index.tsx")
      return { default: mod.PostButton || mod.default }
    }),
    categories: ["social"],
    dependencies: undefined,
  },
  "like-button": {
    name: "like-button",
    title: "Like Button",
    description: "Optimistic like/unlike toggle for BSocial content",
    type: "registry:block",
    registryDependencies: undefined,
    files: [{
      path: "registry/bigblocks/blocks/like-button/index.tsx",
      type: "registry:block",
      target: ""
    }, {
      path: "registry/bigblocks/blocks/like-button/ui.tsx",
      type: "registry:component",
      target: ""
    }, {
      path: "registry/bigblocks/blocks/like-button/use-like.ts",
      type: "registry:hook",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bigblocks/blocks/like-button/index.tsx")
      return { default: mod.LikeButton || mod.default }
    }),
    categories: ["social"],
    dependencies: undefined,
  },
  "follow-button": {
    name: "follow-button",
    title: "Follow Button",
    description: "Three-state follow/following/unfollow toggle",
    type: "registry:block",
    registryDependencies: undefined,
    files: [{
      path: "registry/bigblocks/blocks/follow-button/index.tsx",
      type: "registry:block",
      target: ""
    }, {
      path: "registry/bigblocks/blocks/follow-button/ui.tsx",
      type: "registry:component",
      target: ""
    }, {
      path: "registry/bigblocks/blocks/follow-button/use-follow.ts",
      type: "registry:hook",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bigblocks/blocks/follow-button/index.tsx")
      return { default: mod.FollowButton || mod.default }
    }),
    categories: ["social"],
    dependencies: undefined,
  },
  "friend-button": {
    name: "friend-button",
    title: "Friend Button",
    description: "Four-state friend request button with accept/decline",
    type: "registry:block",
    registryDependencies: undefined,
    files: [{
      path: "registry/bigblocks/blocks/friend-button/index.tsx",
      type: "registry:block",
      target: ""
    }, {
      path: "registry/bigblocks/blocks/friend-button/ui.tsx",
      type: "registry:component",
      target: ""
    }, {
      path: "registry/bigblocks/blocks/friend-button/use-friend.ts",
      type: "registry:hook",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bigblocks/blocks/friend-button/index.tsx")
      return { default: mod.FriendButton || mod.default }
    }),
    categories: ["social"],
    dependencies: undefined,
  },
  "social-feed": {
    name: "social-feed",
    title: "Social Feed",
    description: "Chronological feed of on-chain BSocial posts",
    type: "registry:block",
    registryDependencies: undefined,
    files: [{
      path: "registry/bigblocks/blocks/social-feed/index.tsx",
      type: "registry:block",
      target: ""
    }, {
      path: "registry/bigblocks/blocks/social-feed/social-feed-ui.tsx",
      type: "registry:component",
      target: ""
    }, {
      path: "registry/bigblocks/blocks/social-feed/post-card-ui.tsx",
      type: "registry:component",
      target: ""
    }, {
      path: "registry/bigblocks/blocks/social-feed/use-social-feed.ts",
      type: "registry:hook",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bigblocks/blocks/social-feed/index.tsx")
      return { default: mod.SocialFeed || mod.default }
    }),
    categories: ["social"],
    dependencies: undefined,
  },
  "inscribe-file": {
    name: "inscribe-file",
    title: "Inscribe File",
    description: "Full inscription flow with file upload, BSV20/BSV21 tabs, and metadata",
    type: "registry:block",
    registryDependencies: undefined,
    files: [{
      path: "registry/bigblocks/blocks/inscribe-file/index.tsx",
      type: "registry:block",
      target: ""
    }, {
      path: "registry/bigblocks/blocks/inscribe-file/inscribe-dropzone.tsx",
      type: "registry:component",
      target: ""
    }, {
      path: "registry/bigblocks/blocks/inscribe-file/inscribe-form.tsx",
      type: "registry:component",
      target: ""
    }, {
      path: "registry/bigblocks/blocks/inscribe-file/content-type-select.tsx",
      type: "registry:component",
      target: ""
    }, {
      path: "registry/bigblocks/blocks/inscribe-file/bsv20-form.tsx",
      type: "registry:component",
      target: ""
    }, {
      path: "registry/bigblocks/blocks/inscribe-file/bsv21-form.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bigblocks/blocks/inscribe-file/index.tsx")
      return { default: mod.InscribeFile || mod.default }
    }),
    categories: ["market"],
    dependencies: undefined,
  },
  "deploy-token": {
    name: "deploy-token",
    title: "Deploy Token",
    description: "Deploy BSV21 fungible tokens with icon upload",
    type: "registry:block",
    registryDependencies: undefined,
    files: [{
      path: "registry/bigblocks/blocks/deploy-token/index.tsx",
      type: "registry:block",
      target: ""
    }, {
      path: "registry/bigblocks/blocks/deploy-token/ui.tsx",
      type: "registry:component",
      target: ""
    }, {
      path: "registry/bigblocks/blocks/deploy-token/use-deploy-token.ts",
      type: "registry:hook",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bigblocks/blocks/deploy-token/index.tsx")
      return { default: mod.DeployToken || mod.default }
    }),
    categories: ["market"],
    dependencies: undefined,
  },
  "create-listing": {
    name: "create-listing",
    title: "Create Listing",
    description: "List ordinal NFTs for sale via OrdLock contract",
    type: "registry:block",
    registryDependencies: undefined,
    files: [{
      path: "registry/bigblocks/blocks/create-listing/index.tsx",
      type: "registry:block",
      target: ""
    }, {
      path: "registry/bigblocks/blocks/create-listing/ui.tsx",
      type: "registry:component",
      target: ""
    }, {
      path: "registry/bigblocks/blocks/create-listing/use-create-listing.ts",
      type: "registry:hook",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bigblocks/blocks/create-listing/index.tsx")
      return { default: mod.CreateListing || mod.default }
    }),
    categories: ["market"],
    dependencies: undefined,
  },
  "buy-listing": {
    name: "buy-listing",
    title: "Buy Listing",
    description: "Purchase ordinal NFTs from the global orderbook",
    type: "registry:block",
    registryDependencies: undefined,
    files: [{
      path: "registry/bigblocks/blocks/buy-listing/index.tsx",
      type: "registry:block",
      target: ""
    }, {
      path: "registry/bigblocks/blocks/buy-listing/ui.tsx",
      type: "registry:component",
      target: ""
    }, {
      path: "registry/bigblocks/blocks/buy-listing/use-buy-listing.ts",
      type: "registry:hook",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bigblocks/blocks/buy-listing/index.tsx")
      return { default: mod.BuyListing || mod.default }
    }),
    categories: ["market"],
    dependencies: undefined,
  },
  "ordinals-grid": {
    name: "ordinals-grid",
    title: "Ordinals Grid",
    description: "Responsive grid of owned ordinal NFTs with ORDFS thumbnails",
    type: "registry:block",
    registryDependencies: undefined,
    files: [{
      path: "registry/bigblocks/blocks/ordinals-grid/index.tsx",
      type: "registry:block",
      target: ""
    }, {
      path: "registry/bigblocks/blocks/ordinals-grid/ordinals-grid-ui.tsx",
      type: "registry:component",
      target: ""
    }, {
      path: "registry/bigblocks/blocks/ordinals-grid/use-ordinals-grid.ts",
      type: "registry:hook",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bigblocks/blocks/ordinals-grid/index.tsx")
      return { default: mod.OrdinalsGrid || mod.default }
    }),
    categories: ["market"],
    dependencies: undefined,
  },
  "market-grid": {
    name: "market-grid",
    title: "Market Grid",
    description: "Global orderbook grid with listings and buy actions",
    type: "registry:block",
    registryDependencies: undefined,
    files: [{
      path: "registry/bigblocks/blocks/market-grid/index.tsx",
      type: "registry:block",
      target: ""
    }, {
      path: "registry/bigblocks/blocks/market-grid/market-grid-ui.tsx",
      type: "registry:component",
      target: ""
    }, {
      path: "registry/bigblocks/blocks/market-grid/listing-card-ui.tsx",
      type: "registry:component",
      target: ""
    }, {
      path: "registry/bigblocks/blocks/market-grid/use-market-grid.ts",
      type: "registry:hook",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bigblocks/blocks/market-grid/index.tsx")
      return { default: mod.MarketGrid || mod.default }
    }),
    categories: ["market"],
    dependencies: undefined,
  },
  "bitcoin-avatar": {
    name: "bitcoin-avatar",
    title: "Bitcoin Avatar",
    description: "On-chain image resolution with deterministic sigma-avatars fallback",
    type: "registry:block",
    registryDependencies: undefined,
    files: [{
      path: "registry/bigblocks/blocks/bitcoin-avatar/index.tsx",
      type: "registry:block",
      target: ""
    }, {
      path: "registry/bigblocks/blocks/bitcoin-avatar/ui.tsx",
      type: "registry:component",
      target: ""
    }, {
      path: "registry/bigblocks/blocks/bitcoin-avatar/use-bitcoin-avatar.ts",
      type: "registry:hook",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bigblocks/blocks/bitcoin-avatar/index.tsx")
      return { default: mod.BitcoinAvatar || mod.default }
    }),
    categories: ["identity"],
    dependencies: undefined,
  },
  "profile-card": {
    name: "profile-card",
    title: "Profile Card",
    description: "Display BAP identity profile with avatar, name, bio",
    type: "registry:block",
    registryDependencies: undefined,
    files: [{
      path: "registry/bigblocks/blocks/profile-card/index.tsx",
      type: "registry:block",
      target: ""
    }, {
      path: "registry/bigblocks/blocks/profile-card/profile-card-ui.tsx",
      type: "registry:component",
      target: ""
    }, {
      path: "registry/bigblocks/blocks/profile-card/use-profile-card.ts",
      type: "registry:hook",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bigblocks/blocks/profile-card/index.tsx")
      return { default: mod.ProfileCard || mod.default }
    }),
    categories: ["identity"],
    dependencies: undefined,
  },
  "identity-selector": {
    name: "identity-selector",
    title: "Identity Selector",
    description: "Switch between BAP identities with active indicator",
    type: "registry:block",
    registryDependencies: undefined,
    files: [{
      path: "registry/bigblocks/blocks/identity-selector/index.tsx",
      type: "registry:block",
      target: ""
    }, {
      path: "registry/bigblocks/blocks/identity-selector/identity-selector-ui.tsx",
      type: "registry:component",
      target: ""
    }, {
      path: "registry/bigblocks/blocks/identity-selector/use-identity-selector.ts",
      type: "registry:hook",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bigblocks/blocks/identity-selector/index.tsx")
      return { default: mod.IdentitySelector || mod.default }
    }),
    categories: ["identity"],
    dependencies: undefined,
  },
  "opns-manager": {
    name: "opns-manager",
    title: "OpNS Manager",
    description: "OpNS name management block for listing owned names and registering or deregistering identity key bindings",
    type: "registry:block",
    registryDependencies: undefined,
    files: [{
      path: "registry/bigblocks/blocks/opns-manager/index.tsx",
      type: "registry:block",
      target: ""
    }, {
      path: "registry/bigblocks/blocks/opns-manager/opns-manager-ui.tsx",
      type: "registry:component",
      target: ""
    }, {
      path: "registry/bigblocks/blocks/opns-manager/use-opns-manager.ts",
      type: "registry:hook",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bigblocks/blocks/opns-manager/index.tsx")
      return { default: mod.OpnsManager || mod.default }
    }),
    categories: ["identity"],
    dependencies: undefined,
  },
  "theme-token-provider": {
    name: "theme-token-provider",
    title: "Theme Token Provider",
    description: "On-chain theme picker using @theme-token/sdk with provider context and settings panel",
    type: "registry:block",
    registryDependencies: undefined,
    files: [{
      path: "registry/bigblocks/blocks/theme-token-provider/index.tsx",
      type: "registry:block",
      target: ""
    }, {
      path: "registry/bigblocks/blocks/theme-token-provider/theme-token-settings-ui.tsx",
      type: "registry:component",
      target: ""
    }, {
      path: "registry/bigblocks/blocks/theme-token-provider/use-theme-token.ts",
      type: "registry:hook",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bigblocks/blocks/theme-token-provider/index.tsx")
      return { default: mod.ThemeTokenProvider || mod.default }
    }),
    categories: ["developer"],
    dependencies: undefined,
  },
  "bigblocks-provider": {
    name: "bigblocks-provider",
    title: "BigBlocks Provider",
    description: "Context provider that configures how all BigBlocks hooks fetch data with web and custom modes",
    type: "registry:lib",
    registryDependencies: undefined,
    files: [{
      path: "registry/bigblocks/blocks/bigblocks-provider/index.tsx",
      type: "registry:lib",
      target: ""
    }, {
      path: "registry/bigblocks/blocks/bigblocks-provider/bigblocks-context.ts",
      type: "registry:lib",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bigblocks/blocks/bigblocks-provider/index.tsx")
      return { default: mod.BigBlocksProvider || mod.default }
    }),
    categories: ["developer"],
    dependencies: undefined,
  },
  "step-indicator-demo": {
    name: "step-indicator-demo",
    type: "registry:example",
    registryDependencies: ["step-indicator"],
    files: [{
      path: "registry/bigblocks/examples/step-indicator-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/bigblocks/examples/step-indicator-demo.tsx")),
    categories: ["examples"],
  },
  "step-indicator-vertical": {
    name: "step-indicator-vertical",
    type: "registry:example",
    registryDependencies: ["step-indicator"],
    files: [{
      path: "registry/bigblocks/examples/step-indicator-vertical.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/bigblocks/examples/step-indicator-vertical.tsx")),
    categories: ["examples"],
  },
  "step-indicator-with-descriptions": {
    name: "step-indicator-with-descriptions",
    type: "registry:example",
    registryDependencies: ["step-indicator"],
    files: [{
      path: "registry/bigblocks/examples/step-indicator-with-descriptions.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/bigblocks/examples/step-indicator-with-descriptions.tsx")),
    categories: ["examples"],
  },
  "connect-wallet-demo": {
    name: "connect-wallet-demo",
    type: "registry:example",
    registryDependencies: ["connect-wallet"],
    files: [{
      path: "registry/bigblocks/examples/connect-wallet-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/bigblocks/examples/connect-wallet-demo.tsx")),
    categories: ["examples"],
  },
  "connect-wallet-compact": {
    name: "connect-wallet-compact",
    type: "registry:example",
    registryDependencies: ["connect-wallet"],
    files: [{
      path: "registry/bigblocks/examples/connect-wallet-compact.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/bigblocks/examples/connect-wallet-compact.tsx")),
    categories: ["examples"],
  },
  "send-bsv-demo": {
    name: "send-bsv-demo",
    type: "registry:example",
    registryDependencies: ["send-bsv"],
    files: [{
      path: "registry/bigblocks/examples/send-bsv-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/bigblocks/examples/send-bsv-demo.tsx")),
    categories: ["examples"],
  },
  "send-bsv-compact": {
    name: "send-bsv-compact",
    type: "registry:example",
    registryDependencies: ["send-bsv"],
    files: [{
      path: "registry/bigblocks/examples/send-bsv-compact.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/bigblocks/examples/send-bsv-compact.tsx")),
    categories: ["examples"],
  },
  "send-bsv-quick": {
    name: "send-bsv-quick",
    type: "registry:example",
    registryDependencies: ["send-bsv"],
    files: [{
      path: "registry/bigblocks/examples/send-bsv-quick.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/bigblocks/examples/send-bsv-quick.tsx")),
    categories: ["examples"],
  },
  "token-list-demo": {
    name: "token-list-demo",
    type: "registry:example",
    registryDependencies: ["token-list"],
    files: [{
      path: "registry/bigblocks/examples/token-list-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/bigblocks/examples/token-list-demo.tsx")),
    categories: ["examples"],
  },
  "receive-address-demo": {
    name: "receive-address-demo",
    type: "registry:example",
    registryDependencies: ["receive-address"],
    files: [{
      path: "registry/bigblocks/examples/receive-address-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/bigblocks/examples/receive-address-demo.tsx")),
    categories: ["examples"],
  },
  "transaction-history-demo": {
    name: "transaction-history-demo",
    type: "registry:example",
    registryDependencies: ["transaction-history"],
    files: [{
      path: "registry/bigblocks/examples/transaction-history-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/bigblocks/examples/transaction-history-demo.tsx")),
    categories: ["examples"],
  },
  "mnemonic-flow-demo": {
    name: "mnemonic-flow-demo",
    type: "registry:example",
    registryDependencies: ["mnemonic-flow"],
    files: [{
      path: "registry/bigblocks/examples/mnemonic-flow-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/bigblocks/examples/mnemonic-flow-demo.tsx")),
    categories: ["examples"],
  },
  "sync-terminal-demo": {
    name: "sync-terminal-demo",
    type: "registry:example",
    registryDependencies: ["sync-terminal"],
    files: [{
      path: "registry/bigblocks/examples/sync-terminal-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/bigblocks/examples/sync-terminal-demo.tsx")),
    categories: ["examples"],
  },
  "lock-bsv-demo": {
    name: "lock-bsv-demo",
    type: "registry:example",
    registryDependencies: ["lock-bsv"],
    files: [{
      path: "registry/bigblocks/examples/lock-bsv-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/bigblocks/examples/lock-bsv-demo.tsx")),
    categories: ["examples"],
  },
  "sweep-wallet-demo": {
    name: "sweep-wallet-demo",
    type: "registry:example",
    registryDependencies: ["sweep-wallet"],
    files: [{
      path: "registry/bigblocks/examples/sweep-wallet-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/bigblocks/examples/sweep-wallet-demo.tsx")),
    categories: ["examples"],
  },
  "send-bsv21-demo": {
    name: "send-bsv21-demo",
    type: "registry:example",
    registryDependencies: ["send-bsv21"],
    files: [{
      path: "registry/bigblocks/examples/send-bsv21-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/bigblocks/examples/send-bsv21-demo.tsx")),
    categories: ["examples"],
  },
  "unlock-wallet-demo": {
    name: "unlock-wallet-demo",
    type: "registry:example",
    registryDependencies: ["unlock-wallet"],
    files: [{
      path: "registry/bigblocks/examples/unlock-wallet-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/bigblocks/examples/unlock-wallet-demo.tsx")),
    categories: ["examples"],
  },
  "wallet-overview-demo": {
    name: "wallet-overview-demo",
    type: "registry:example",
    registryDependencies: ["wallet-overview"],
    files: [{
      path: "registry/bigblocks/examples/wallet-overview-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/bigblocks/examples/wallet-overview-demo.tsx")),
    categories: ["examples"],
  },
  "post-button-demo": {
    name: "post-button-demo",
    type: "registry:example",
    registryDependencies: ["post-button"],
    files: [{
      path: "registry/bigblocks/examples/post-button-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/bigblocks/examples/post-button-demo.tsx")),
    categories: ["examples"],
  },
  "post-button-compact": {
    name: "post-button-compact",
    type: "registry:example",
    registryDependencies: ["post-button"],
    files: [{
      path: "registry/bigblocks/examples/post-button-compact.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/bigblocks/examples/post-button-compact.tsx")),
    categories: ["examples"],
  },
  "post-button-inline": {
    name: "post-button-inline",
    type: "registry:example",
    registryDependencies: ["post-button"],
    files: [{
      path: "registry/bigblocks/examples/post-button-inline.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/bigblocks/examples/post-button-inline.tsx")),
    categories: ["examples"],
  },
  "like-button-demo": {
    name: "like-button-demo",
    type: "registry:example",
    registryDependencies: ["like-button"],
    files: [{
      path: "registry/bigblocks/examples/like-button-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/bigblocks/examples/like-button-demo.tsx")),
    categories: ["examples"],
  },
  "like-button-liked": {
    name: "like-button-liked",
    type: "registry:example",
    registryDependencies: ["like-button"],
    files: [{
      path: "registry/bigblocks/examples/like-button-liked.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/bigblocks/examples/like-button-liked.tsx")),
    categories: ["examples"],
  },
  "like-button-compact": {
    name: "like-button-compact",
    type: "registry:example",
    registryDependencies: ["like-button"],
    files: [{
      path: "registry/bigblocks/examples/like-button-compact.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/bigblocks/examples/like-button-compact.tsx")),
    categories: ["examples"],
  },
  "like-button-text": {
    name: "like-button-text",
    type: "registry:example",
    registryDependencies: ["like-button"],
    files: [{
      path: "registry/bigblocks/examples/like-button-text.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/bigblocks/examples/like-button-text.tsx")),
    categories: ["examples"],
  },
  "follow-button-demo": {
    name: "follow-button-demo",
    type: "registry:example",
    registryDependencies: ["follow-button"],
    files: [{
      path: "registry/bigblocks/examples/follow-button-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/bigblocks/examples/follow-button-demo.tsx")),
    categories: ["examples"],
  },
  "follow-button-compact": {
    name: "follow-button-compact",
    type: "registry:example",
    registryDependencies: ["follow-button"],
    files: [{
      path: "registry/bigblocks/examples/follow-button-compact.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/bigblocks/examples/follow-button-compact.tsx")),
    categories: ["examples"],
  },
  "follow-button-states": {
    name: "follow-button-states",
    type: "registry:example",
    registryDependencies: ["follow-button"],
    files: [{
      path: "registry/bigblocks/examples/follow-button-states.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/bigblocks/examples/follow-button-states.tsx")),
    categories: ["examples"],
  },
  "friend-button-demo": {
    name: "friend-button-demo",
    type: "registry:example",
    registryDependencies: ["friend-button"],
    files: [{
      path: "registry/bigblocks/examples/friend-button-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/bigblocks/examples/friend-button-demo.tsx")),
    categories: ["examples"],
  },
  "friend-button-pending": {
    name: "friend-button-pending",
    type: "registry:example",
    registryDependencies: ["friend-button"],
    files: [{
      path: "registry/bigblocks/examples/friend-button-pending.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/bigblocks/examples/friend-button-pending.tsx")),
    categories: ["examples"],
  },
  "friend-button-received": {
    name: "friend-button-received",
    type: "registry:example",
    registryDependencies: ["friend-button"],
    files: [{
      path: "registry/bigblocks/examples/friend-button-received.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/bigblocks/examples/friend-button-received.tsx")),
    categories: ["examples"],
  },
  "friend-button-friends": {
    name: "friend-button-friends",
    type: "registry:example",
    registryDependencies: ["friend-button"],
    files: [{
      path: "registry/bigblocks/examples/friend-button-friends.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/bigblocks/examples/friend-button-friends.tsx")),
    categories: ["examples"],
  },
  "social-feed-demo": {
    name: "social-feed-demo",
    type: "registry:example",
    registryDependencies: ["social-feed"],
    files: [{
      path: "registry/bigblocks/examples/social-feed-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/bigblocks/examples/social-feed-demo.tsx")),
    categories: ["examples"],
  },
  "inscribe-file-demo": {
    name: "inscribe-file-demo",
    type: "registry:example",
    registryDependencies: ["inscribe-file"],
    files: [{
      path: "registry/bigblocks/examples/inscribe-file-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/bigblocks/examples/inscribe-file-demo.tsx")),
    categories: ["examples"],
  },
  "deploy-token-demo": {
    name: "deploy-token-demo",
    type: "registry:example",
    registryDependencies: ["deploy-token"],
    files: [{
      path: "registry/bigblocks/examples/deploy-token-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/bigblocks/examples/deploy-token-demo.tsx")),
    categories: ["examples"],
  },
  "create-listing-demo": {
    name: "create-listing-demo",
    type: "registry:example",
    registryDependencies: ["create-listing"],
    files: [{
      path: "registry/bigblocks/examples/create-listing-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/bigblocks/examples/create-listing-demo.tsx")),
    categories: ["examples"],
  },
  "buy-listing-demo": {
    name: "buy-listing-demo",
    type: "registry:example",
    registryDependencies: ["buy-listing"],
    files: [{
      path: "registry/bigblocks/examples/buy-listing-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/bigblocks/examples/buy-listing-demo.tsx")),
    categories: ["examples"],
  },
  "ordinals-grid-demo": {
    name: "ordinals-grid-demo",
    type: "registry:example",
    registryDependencies: ["ordinals-grid"],
    files: [{
      path: "registry/bigblocks/examples/ordinals-grid-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/bigblocks/examples/ordinals-grid-demo.tsx")),
    categories: ["examples"],
  },
  "market-grid-demo": {
    name: "market-grid-demo",
    type: "registry:example",
    registryDependencies: ["market-grid"],
    files: [{
      path: "registry/bigblocks/examples/market-grid-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/bigblocks/examples/market-grid-demo.tsx")),
    categories: ["examples"],
  },
  "bitcoin-avatar-demo": {
    name: "bitcoin-avatar-demo",
    type: "registry:example",
    registryDependencies: ["bitcoin-avatar"],
    files: [{
      path: "registry/bigblocks/examples/bitcoin-avatar-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/bigblocks/examples/bitcoin-avatar-demo.tsx")),
    categories: ["examples"],
  },
  "bitcoin-avatar-variants": {
    name: "bitcoin-avatar-variants",
    type: "registry:example",
    registryDependencies: ["bitcoin-avatar"],
    files: [{
      path: "registry/bigblocks/examples/bitcoin-avatar-variants.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/bigblocks/examples/bitcoin-avatar-variants.tsx")),
    categories: ["examples"],
  },
  "profile-card-demo": {
    name: "profile-card-demo",
    type: "registry:example",
    registryDependencies: ["profile-card"],
    files: [{
      path: "registry/bigblocks/examples/profile-card-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/bigblocks/examples/profile-card-demo.tsx")),
    categories: ["examples"],
  },
  "identity-selector-demo": {
    name: "identity-selector-demo",
    type: "registry:example",
    registryDependencies: ["identity-selector"],
    files: [{
      path: "registry/bigblocks/examples/identity-selector-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/bigblocks/examples/identity-selector-demo.tsx")),
    categories: ["examples"],
  },
  "opns-manager-demo": {
    name: "opns-manager-demo",
    type: "registry:example",
    registryDependencies: ["opns-manager"],
    files: [{
      path: "registry/bigblocks/examples/opns-manager-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/bigblocks/examples/opns-manager-demo.tsx")),
    categories: ["examples"],
  },
  "theme-token-provider-demo": {
    name: "theme-token-provider-demo",
    type: "registry:example",
    registryDependencies: ["theme-token-provider"],
    files: [{
      path: "registry/bigblocks/examples/theme-token-provider-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/bigblocks/examples/theme-token-provider-demo.tsx")),
    categories: ["examples"],
  },
  "bigblocks-provider-demo": {
    name: "bigblocks-provider-demo",
    type: "registry:example",
    registryDependencies: ["bigblocks-provider"],
    files: [{
      path: "registry/bigblocks/examples/bigblocks-provider-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/bigblocks/examples/bigblocks-provider-demo.tsx")),
    categories: ["examples"],
  },
}
