/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.mts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "step-indicator": {
    name: "step-indicator",
    title: "Step Indicator",
    description: "Display progress through multi-step processes with horizontal and vertical variants",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/bigblocks/ui/step-indicator.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/bigblocks/ui/step-indicator.tsx")
      return { default: mod.StepIndicator || mod.default }
    }),
    categories: ["ui-components"],
    dependencies: ["@radix-ui/react-icons"],
  },
  "step-indicator-demo": {
    name: "step-indicator-demo",
    title: "Step Indicator Demo",
    description: "Interactive demo of the step indicator component",
    type: "registry:example",
    files: [{
      path: "registry/bigblocks/examples/step-indicator-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/bigblocks/examples/step-indicator-demo.tsx")),
    categories: ["examples"],
  },
  "step-indicator-vertical": {
    name: "step-indicator-vertical",
    title: "Step Indicator Vertical",
    description: "Vertical variant of the step indicator",
    type: "registry:example",
    files: [{
      path: "registry/bigblocks/examples/step-indicator-vertical.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/bigblocks/examples/step-indicator-vertical.tsx")),
    categories: ["examples"],
  },
  "step-indicator-with-descriptions": {
    name: "step-indicator-with-descriptions",
    title: "Step Indicator With Descriptions",
    description: "Step indicator with descriptions for each step",
    type: "registry:example",
    files: [{
      path: "registry/bigblocks/examples/step-indicator-with-descriptions.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(() => import("@/registry/bigblocks/examples/step-indicator-with-descriptions.tsx")),
    categories: ["examples"],
  },
}