export const registry = {
  name: "bigblocks",
  items: [
    // ── Existing ──
    {
      name: "step-indicator",
      type: "registry:ui",
      title: "Step Indicator",
      description: "Display progress through multi-step processes with horizontal and vertical variants",
      categories: ["ui-components"],
      files: [{ path: "ui/step-indicator.tsx", type: "registry:ui" }],
      dependencies: ["@radix-ui/react-icons"],
    },

    // ── Wallet ──
    {
      name: "connect-wallet",
      type: "registry:block",
      title: "Connect Wallet",
      description: "Wallet connection button with provider selection and connected-state dropdown",
      categories: ["wallet"],
      files: [
        { path: "blocks/connect-wallet/index.tsx", type: "registry:block" },
        { path: "blocks/connect-wallet/ui.tsx", type: "registry:component" },
        { path: "blocks/connect-wallet/use-connect-wallet.ts", type: "registry:hook" },
      ],
    },
    {
      name: "send-bsv",
      type: "registry:block",
      title: "Send BSV",
      description: "Complete send BSV block with trigger variants and dialog form",
      categories: ["wallet"],
      files: [
        { path: "blocks/send-bsv/index.tsx", type: "registry:block" },
        { path: "blocks/send-bsv/send-bsv-trigger.tsx", type: "registry:component" },
        { path: "blocks/send-bsv/send-bsv-dialog.tsx", type: "registry:component" },
      ],
    },
    {
      name: "token-list",
      type: "registry:block",
      title: "Token List",
      description: "BSV20/BSV21 token holdings list with balances and icons",
      categories: ["wallet"],
      files: [
        { path: "blocks/token-list/index.tsx", type: "registry:block" },
        { path: "blocks/token-list/token-list-ui.tsx", type: "registry:component" },
        { path: "blocks/token-list/use-token-list.ts", type: "registry:hook" },
      ],
    },
    {
      name: "receive-address",
      type: "registry:block",
      title: "Receive Address",
      description: "QR code and deposit address display with clipboard copy and optional address rotation",
      categories: ["wallet"],
      files: [
        { path: "blocks/receive-address/index.tsx", type: "registry:block" },
        { path: "blocks/receive-address/receive-address-ui.tsx", type: "registry:component" },
        { path: "blocks/receive-address/use-receive-address.ts", type: "registry:hook" },
      ],
    },
    {
      name: "transaction-history",
      type: "registry:block",
      title: "Transaction History",
      description: "Transaction list with status indicators, amounts, relative dates, and pagination",
      categories: ["wallet"],
      files: [
        { path: "blocks/transaction-history/index.tsx", type: "registry:block" },
        { path: "blocks/transaction-history/transaction-history-ui.tsx", type: "registry:component" },
        { path: "blocks/transaction-history/use-transaction-history.ts", type: "registry:hook" },
      ],
    },
    {
      name: "mnemonic-flow",
      type: "registry:block",
      title: "Mnemonic Flow",
      description: "Multi-mode seed phrase display and input block with create, display, import, and verify modes",
      categories: ["wallet"],
      files: [
        { path: "blocks/mnemonic-flow/index.tsx", type: "registry:block" },
        { path: "blocks/mnemonic-flow/mnemonic-flow-ui.tsx", type: "registry:component" },
        { path: "blocks/mnemonic-flow/mnemonic-grid-ui.tsx", type: "registry:component" },
        { path: "blocks/mnemonic-flow/use-mnemonic-flow.ts", type: "registry:hook" },
      ],
    },
    {
      name: "lock-bsv",
      type: "registry:block",
      title: "Lock BSV",
      description: "Time-lock BSV until a future block height with lock form, summary, and unlock for matured locks",
      categories: ["wallet"],
      files: [
        { path: "blocks/lock-bsv/index.tsx", type: "registry:block" },
        { path: "blocks/lock-bsv/lock-bsv-ui.tsx", type: "registry:component" },
        { path: "blocks/lock-bsv/use-lock-bsv.ts", type: "registry:hook" },
      ],
    },
    {
      name: "sweep-wallet",
      type: "registry:block",
      title: "Sweep Wallet",
      description: "Sweep assets from a WIF private key into the connected wallet with scan and progress",
      categories: ["wallet"],
      files: [
        { path: "blocks/sweep-wallet/index.tsx", type: "registry:block" },
        { path: "blocks/sweep-wallet/sweep-wallet-ui.tsx", type: "registry:component" },
        { path: "blocks/sweep-wallet/use-sweep-wallet.ts", type: "registry:hook" },
      ],
    },
    {
      name: "send-bsv21",
      type: "registry:block",
      title: "Send BSV21",
      description: "Token send form with selector dropdown, decimal-aware amount input, and confirmation flow",
      categories: ["wallet"],
      files: [
        { path: "blocks/send-bsv21/index.tsx", type: "registry:block" },
        { path: "blocks/send-bsv21/send-bsv21-ui.tsx", type: "registry:component" },
        { path: "blocks/send-bsv21/use-send-bsv21.ts", type: "registry:hook" },
      ],
    },
    {
      name: "unlock-wallet",
      type: "registry:block",
      title: "Unlock Wallet",
      description: "Passphrase and biometric unlock screen with Touch ID support and failed attempt tracking",
      categories: ["wallet"],
      files: [
        { path: "blocks/unlock-wallet/index.tsx", type: "registry:block" },
        { path: "blocks/unlock-wallet/unlock-wallet-ui.tsx", type: "registry:component" },
        { path: "blocks/unlock-wallet/use-unlock-wallet.ts", type: "registry:hook" },
      ],
    },
    {
      name: "wallet-overview",
      type: "registry:block",
      title: "Wallet Overview",
      description: "Wallet dashboard card with BSV balance, privacy toggle, addresses, and send/receive actions",
      categories: ["wallet"],
      files: [
        { path: "blocks/wallet-overview/index.tsx", type: "registry:block" },
        { path: "blocks/wallet-overview/wallet-overview-ui.tsx", type: "registry:component" },
        { path: "blocks/wallet-overview/use-wallet-overview.ts", type: "registry:hook" },
      ],
    },
    {
      name: "sync-terminal",
      type: "registry:block",
      title: "Sync Terminal",
      description: "Monospace event log for blockchain sync activity with colour-coded severity levels",
      categories: ["developer"],
      files: [
        { path: "blocks/sync-terminal/index.tsx", type: "registry:block" },
        { path: "blocks/sync-terminal/sync-terminal-ui.tsx", type: "registry:component" },
        { path: "blocks/sync-terminal/use-sync-terminal.ts", type: "registry:hook" },
      ],
    },

    // ── Social ──
    {
      name: "post-button",
      type: "registry:block",
      title: "Post Button",
      description: "Create on-chain BSocial posts with compose dialog",
      categories: ["social"],
      files: [
        { path: "blocks/post-button/index.tsx", type: "registry:block" },
        { path: "blocks/post-button/ui.tsx", type: "registry:component" },
        { path: "blocks/post-button/use-post.ts", type: "registry:hook" },
      ],
    },
    {
      name: "like-button",
      type: "registry:block",
      title: "Like Button",
      description: "Optimistic like/unlike toggle for BSocial content",
      categories: ["social"],
      files: [
        { path: "blocks/like-button/index.tsx", type: "registry:block" },
        { path: "blocks/like-button/ui.tsx", type: "registry:component" },
        { path: "blocks/like-button/use-like.ts", type: "registry:hook" },
      ],
    },
    {
      name: "follow-button",
      type: "registry:block",
      title: "Follow Button",
      description: "Three-state follow/following/unfollow toggle",
      categories: ["social"],
      files: [
        { path: "blocks/follow-button/index.tsx", type: "registry:block" },
        { path: "blocks/follow-button/ui.tsx", type: "registry:component" },
        { path: "blocks/follow-button/use-follow.ts", type: "registry:hook" },
      ],
    },
    {
      name: "friend-button",
      type: "registry:block",
      title: "Friend Button",
      description: "Four-state friend request button with accept/decline",
      categories: ["social"],
      files: [
        { path: "blocks/friend-button/index.tsx", type: "registry:block" },
        { path: "blocks/friend-button/ui.tsx", type: "registry:component" },
        { path: "blocks/friend-button/use-friend.ts", type: "registry:hook" },
      ],
    },
    {
      name: "social-feed",
      type: "registry:block",
      title: "Social Feed",
      description: "Chronological feed of on-chain BSocial posts",
      categories: ["social"],
      files: [
        { path: "blocks/social-feed/index.tsx", type: "registry:block" },
        { path: "blocks/social-feed/social-feed-ui.tsx", type: "registry:component" },
        { path: "blocks/social-feed/post-card-ui.tsx", type: "registry:component" },
        { path: "blocks/social-feed/use-social-feed.ts", type: "registry:hook" },
      ],
    },

    // ── Marketplace ──
    {
      name: "inscribe-file",
      type: "registry:block",
      title: "Inscribe File",
      description: "Full inscription flow with file upload, BSV20/BSV21 tabs, and metadata",
      categories: ["market"],
      files: [
        { path: "blocks/inscribe-file/index.tsx", type: "registry:block" },
        { path: "blocks/inscribe-file/inscribe-dropzone.tsx", type: "registry:component" },
        { path: "blocks/inscribe-file/inscribe-form.tsx", type: "registry:component" },
        { path: "blocks/inscribe-file/content-type-select.tsx", type: "registry:component" },
        { path: "blocks/inscribe-file/bsv20-form.tsx", type: "registry:component" },
        { path: "blocks/inscribe-file/bsv21-form.tsx", type: "registry:component" },
      ],
    },
    {
      name: "deploy-token",
      type: "registry:block",
      title: "Deploy Token",
      description: "Deploy BSV21 fungible tokens with icon upload",
      categories: ["market"],
      files: [
        { path: "blocks/deploy-token/index.tsx", type: "registry:block" },
        { path: "blocks/deploy-token/ui.tsx", type: "registry:component" },
        { path: "blocks/deploy-token/use-deploy-token.ts", type: "registry:hook" },
      ],
    },
    {
      name: "create-listing",
      type: "registry:block",
      title: "Create Listing",
      description: "List ordinal NFTs for sale via OrdLock contract",
      categories: ["market"],
      files: [
        { path: "blocks/create-listing/index.tsx", type: "registry:block" },
        { path: "blocks/create-listing/ui.tsx", type: "registry:component" },
        { path: "blocks/create-listing/use-create-listing.ts", type: "registry:hook" },
      ],
    },
    {
      name: "buy-listing",
      type: "registry:block",
      title: "Buy Listing",
      description: "Purchase ordinal NFTs from the global orderbook",
      categories: ["market"],
      files: [
        { path: "blocks/buy-listing/index.tsx", type: "registry:block" },
        { path: "blocks/buy-listing/ui.tsx", type: "registry:component" },
        { path: "blocks/buy-listing/use-buy-listing.ts", type: "registry:hook" },
      ],
    },
    {
      name: "ordinals-grid",
      type: "registry:block",
      title: "Ordinals Grid",
      description: "Responsive grid of owned ordinal NFTs with ORDFS thumbnails",
      categories: ["market"],
      files: [
        { path: "blocks/ordinals-grid/index.tsx", type: "registry:block" },
        { path: "blocks/ordinals-grid/ordinals-grid-ui.tsx", type: "registry:component" },
        { path: "blocks/ordinals-grid/use-ordinals-grid.ts", type: "registry:hook" },
      ],
    },
    {
      name: "market-grid",
      type: "registry:block",
      title: "Market Grid",
      description: "Global orderbook grid with listings and buy actions",
      categories: ["market"],
      files: [
        { path: "blocks/market-grid/index.tsx", type: "registry:block" },
        { path: "blocks/market-grid/market-grid-ui.tsx", type: "registry:component" },
        { path: "blocks/market-grid/listing-card-ui.tsx", type: "registry:component" },
        { path: "blocks/market-grid/use-market-grid.ts", type: "registry:hook" },
      ],
    },

    // ── Identity ──
    {
      name: "bitcoin-avatar",
      type: "registry:block",
      title: "Bitcoin Avatar",
      description: "On-chain image resolution with deterministic sigma-avatars fallback",
      categories: ["identity"],
      files: [
        { path: "blocks/bitcoin-avatar/index.tsx", type: "registry:block" },
        { path: "blocks/bitcoin-avatar/ui.tsx", type: "registry:component" },
        { path: "blocks/bitcoin-avatar/use-bitcoin-avatar.ts", type: "registry:hook" },
      ],
    },
    {
      name: "profile-card",
      type: "registry:block",
      title: "Profile Card",
      description: "Display BAP identity profile with avatar, name, bio",
      categories: ["identity"],
      files: [
        { path: "blocks/profile-card/index.tsx", type: "registry:block" },
        { path: "blocks/profile-card/profile-card-ui.tsx", type: "registry:component" },
        { path: "blocks/profile-card/use-profile-card.ts", type: "registry:hook" },
      ],
    },
    {
      name: "identity-selector",
      type: "registry:block",
      title: "Identity Selector",
      description: "Switch between BAP identities with active indicator",
      categories: ["identity"],
      files: [
        { path: "blocks/identity-selector/index.tsx", type: "registry:block" },
        { path: "blocks/identity-selector/identity-selector-ui.tsx", type: "registry:component" },
        { path: "blocks/identity-selector/use-identity-selector.ts", type: "registry:hook" },
      ],
    },
    {
      name: "opns-manager",
      type: "registry:block",
      title: "OpNS Manager",
      description: "OpNS name management block for listing owned names and registering or deregistering identity key bindings",
      categories: ["identity"],
      files: [
        { path: "blocks/opns-manager/index.tsx", type: "registry:block" },
        { path: "blocks/opns-manager/opns-manager-ui.tsx", type: "registry:component" },
        { path: "blocks/opns-manager/use-opns-manager.ts", type: "registry:hook" },
      ],
    },

    // ── Developer ──
    {
      name: "theme-token-provider",
      type: "registry:block",
      title: "Theme Token Provider",
      description: "On-chain theme picker using @theme-token/sdk with provider context and settings panel",
      categories: ["developer"],
      files: [
        { path: "blocks/theme-token-provider/index.tsx", type: "registry:block" },
        { path: "blocks/theme-token-provider/theme-token-settings-ui.tsx", type: "registry:component" },
        { path: "blocks/theme-token-provider/use-theme-token.ts", type: "registry:hook" },
      ],
    },
    {
      name: "bigblocks-provider",
      type: "registry:lib",
      title: "BigBlocks Provider",
      description: "Context provider that configures how all BigBlocks hooks fetch data with web and custom modes",
      categories: ["developer"],
      files: [
        { path: "blocks/bigblocks-provider/index.tsx", type: "registry:lib" },
        { path: "blocks/bigblocks-provider/bigblocks-context.ts", type: "registry:lib" },
      ],
    },
  ],

  examples: [
    // Step Indicator
    { name: "step-indicator-demo", registryDependencies: ["step-indicator"], files: [{ path: "examples/step-indicator-demo.tsx", type: "registry:example" }] },
    { name: "step-indicator-vertical", registryDependencies: ["step-indicator"], files: [{ path: "examples/step-indicator-vertical.tsx", type: "registry:example" }] },
    { name: "step-indicator-with-descriptions", registryDependencies: ["step-indicator"], files: [{ path: "examples/step-indicator-with-descriptions.tsx", type: "registry:example" }] },

    // Wallet
    { name: "connect-wallet-demo", registryDependencies: ["connect-wallet"], files: [{ path: "examples/connect-wallet-demo.tsx", type: "registry:example" }] },
    { name: "connect-wallet-compact", registryDependencies: ["connect-wallet"], files: [{ path: "examples/connect-wallet-compact.tsx", type: "registry:example" }] },
    { name: "send-bsv-demo", registryDependencies: ["send-bsv"], files: [{ path: "examples/send-bsv-demo.tsx", type: "registry:example" }] },
    { name: "send-bsv-compact", registryDependencies: ["send-bsv"], files: [{ path: "examples/send-bsv-compact.tsx", type: "registry:example" }] },
    { name: "send-bsv-quick", registryDependencies: ["send-bsv"], files: [{ path: "examples/send-bsv-quick.tsx", type: "registry:example" }] },
    { name: "token-list-demo", registryDependencies: ["token-list"], files: [{ path: "examples/token-list-demo.tsx", type: "registry:example" }] },
    { name: "receive-address-demo", registryDependencies: ["receive-address"], files: [{ path: "examples/receive-address-demo.tsx", type: "registry:example" }] },
    { name: "transaction-history-demo", registryDependencies: ["transaction-history"], files: [{ path: "examples/transaction-history-demo.tsx", type: "registry:example" }] },
    { name: "mnemonic-flow-demo", registryDependencies: ["mnemonic-flow"], files: [{ path: "examples/mnemonic-flow-demo.tsx", type: "registry:example" }] },
    { name: "sync-terminal-demo", registryDependencies: ["sync-terminal"], files: [{ path: "examples/sync-terminal-demo.tsx", type: "registry:example" }] },
    { name: "lock-bsv-demo", registryDependencies: ["lock-bsv"], files: [{ path: "examples/lock-bsv-demo.tsx", type: "registry:example" }] },
    { name: "sweep-wallet-demo", registryDependencies: ["sweep-wallet"], files: [{ path: "examples/sweep-wallet-demo.tsx", type: "registry:example" }] },
    { name: "send-bsv21-demo", registryDependencies: ["send-bsv21"], files: [{ path: "examples/send-bsv21-demo.tsx", type: "registry:example" }] },
    { name: "unlock-wallet-demo", registryDependencies: ["unlock-wallet"], files: [{ path: "examples/unlock-wallet-demo.tsx", type: "registry:example" }] },
    { name: "wallet-overview-demo", registryDependencies: ["wallet-overview"], files: [{ path: "examples/wallet-overview-demo.tsx", type: "registry:example" }] },

    // Social
    { name: "post-button-demo", registryDependencies: ["post-button"], files: [{ path: "examples/post-button-demo.tsx", type: "registry:example" }] },
    { name: "post-button-compact", registryDependencies: ["post-button"], files: [{ path: "examples/post-button-compact.tsx", type: "registry:example" }] },
    { name: "post-button-inline", registryDependencies: ["post-button"], files: [{ path: "examples/post-button-inline.tsx", type: "registry:example" }] },
    { name: "like-button-demo", registryDependencies: ["like-button"], files: [{ path: "examples/like-button-demo.tsx", type: "registry:example" }] },
    { name: "like-button-liked", registryDependencies: ["like-button"], files: [{ path: "examples/like-button-liked.tsx", type: "registry:example" }] },
    { name: "like-button-compact", registryDependencies: ["like-button"], files: [{ path: "examples/like-button-compact.tsx", type: "registry:example" }] },
    { name: "like-button-text", registryDependencies: ["like-button"], files: [{ path: "examples/like-button-text.tsx", type: "registry:example" }] },
    { name: "follow-button-demo", registryDependencies: ["follow-button"], files: [{ path: "examples/follow-button-demo.tsx", type: "registry:example" }] },
    { name: "follow-button-compact", registryDependencies: ["follow-button"], files: [{ path: "examples/follow-button-compact.tsx", type: "registry:example" }] },
    { name: "follow-button-states", registryDependencies: ["follow-button"], files: [{ path: "examples/follow-button-states.tsx", type: "registry:example" }] },
    { name: "friend-button-demo", registryDependencies: ["friend-button"], files: [{ path: "examples/friend-button-demo.tsx", type: "registry:example" }] },
    { name: "friend-button-pending", registryDependencies: ["friend-button"], files: [{ path: "examples/friend-button-pending.tsx", type: "registry:example" }] },
    { name: "friend-button-received", registryDependencies: ["friend-button"], files: [{ path: "examples/friend-button-received.tsx", type: "registry:example" }] },
    { name: "friend-button-friends", registryDependencies: ["friend-button"], files: [{ path: "examples/friend-button-friends.tsx", type: "registry:example" }] },
    { name: "social-feed-demo", registryDependencies: ["social-feed"], files: [{ path: "examples/social-feed-demo.tsx", type: "registry:example" }] },

    // Marketplace
    { name: "inscribe-file-demo", registryDependencies: ["inscribe-file"], files: [{ path: "examples/inscribe-file-demo.tsx", type: "registry:example" }] },
    { name: "deploy-token-demo", registryDependencies: ["deploy-token"], files: [{ path: "examples/deploy-token-demo.tsx", type: "registry:example" }] },
    { name: "create-listing-demo", registryDependencies: ["create-listing"], files: [{ path: "examples/create-listing-demo.tsx", type: "registry:example" }] },
    { name: "buy-listing-demo", registryDependencies: ["buy-listing"], files: [{ path: "examples/buy-listing-demo.tsx", type: "registry:example" }] },
    { name: "ordinals-grid-demo", registryDependencies: ["ordinals-grid"], files: [{ path: "examples/ordinals-grid-demo.tsx", type: "registry:example" }] },
    { name: "market-grid-demo", registryDependencies: ["market-grid"], files: [{ path: "examples/market-grid-demo.tsx", type: "registry:example" }] },

    // Identity
    { name: "bitcoin-avatar-demo", registryDependencies: ["bitcoin-avatar"], files: [{ path: "examples/bitcoin-avatar-demo.tsx", type: "registry:example" }] },
    { name: "bitcoin-avatar-variants", registryDependencies: ["bitcoin-avatar"], files: [{ path: "examples/bitcoin-avatar-variants.tsx", type: "registry:example" }] },
    { name: "profile-card-demo", registryDependencies: ["profile-card"], files: [{ path: "examples/profile-card-demo.tsx", type: "registry:example" }] },
    { name: "identity-selector-demo", registryDependencies: ["identity-selector"], files: [{ path: "examples/identity-selector-demo.tsx", type: "registry:example" }] },
    { name: "opns-manager-demo", registryDependencies: ["opns-manager"], files: [{ path: "examples/opns-manager-demo.tsx", type: "registry:example" }] },

    // Developer
    { name: "theme-token-provider-demo", registryDependencies: ["theme-token-provider"], files: [{ path: "examples/theme-token-provider-demo.tsx", type: "registry:example" }] },
    { name: "bigblocks-provider-demo", registryDependencies: ["bigblocks-provider"], files: [{ path: "examples/bigblocks-provider-demo.tsx", type: "registry:example" }] },
  ],
}
